services:

  gateway:
    build: ./gateway
    container_name: shareit-gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SERVER_PORT=8080
      - SERVER_URL=http://server:9090
    restart: on-failure

  server:
    build: ./server
    container_name: shareit-server
    hostname: server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - DB_HOTS=db
      - DB_PORT=5432
      - DB_NAME=shareit
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
      - SERVER_PORT=9090
    restart: on-failure

  db:
    image: postgres:16.1
    container_name: shareit-db
    hostname: db
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
